### ISSUE TITLE
Questions about Presolve

### ISSUE THREAD

**Issue by stumarcus314** [snowberryfield/printemps#209]
Do you know how PRINTEMPS presolve differs from PaPILO presolve and OR-Tools GLOP presolve?

PaPILO:
https://github.com/scipopt/papilo
https://arxiv.org/abs/2206.10709

GLOP Presolve for OR-Tools PDLP:
https://github.com/google/or-tools/blob/5425dedcfbb22cb74c636c1374a9b5ad684b1eb5/ortools/pdlp/solvers.proto#L348

If PRINTEMPS uses presolve, does it need to transform the primal and dual solutions and the upper and lower bounds from the presolved space back to the original space?

Does PRINTEMPS presolve only work for integer linear programming problems?

**Comment by snowberryfield** [comment]
Thank you for providing information on presolving.

>Do you know how PRINTEMPS presolve differs from PaPILO presolve and OR-Tools GLOP presolve?

I'm sorry, but I do not fully understand the details of these softwares and cannot clearly state the differences from PRINTEMP. The presolving techniques incorporated in PRINTEMPS are mainly based on the paper https://www2.isye.gatech.edu/~ms79/software/ojoc6.pdf. (However, some of the techniques described in this paper have not been implemented, while others that are not described in this paper have been implemented.)

>If PRINTEMPS uses presolve, does it need to transform the primal and dual solutions and the upper and lower bounds from the presolved space back to the original space?

No. Presolving techniques employed by PRINTEMPS simply fix the value of variables or eliminate redundant constraints, and there is no need to return back to the original space.  For PDLP, scaling techniques are additionally applied, so the optimal solution obtained by PDLP is different from the optimal solution in the original space. Therefore, after the PDLP is computed, it is automatically mapped to the solution in the original space. However, PRINTEMPS now does not use the main/dual solution mapped to the original space anywhere.

>Does PRINTEMPS presolve only work for integer linear programming problems?

Yes. I believe that some of techniques are applicable to non-linear problem, but I have not addressed it because it would complicate implementation.
